version: "3.8"

services:
  x86-ad-agent:
    # Build the image using the Dockerfile in the current directory (.)
    build: .
    ports:
      - "8080:8080"
    environment:
      OPENAI_MODEL: ${OPENAI_MODEL}
      AZURE_API_VERSION: ${AZURE_API_VERSION}
      AZURE_AD_TOKEN_PROVIDER: ${AZURE_AD_TOKEN_PROVIDER}
      AZURE_ENDPOINT: ${AZURE_ENDPOINT}
    volumes:
      - ~/.azd:/root/.azd
